module.exports = {
    root: true,
    env: { browser: true, es2020: true },
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:react-hooks/recommended',
    ],
    ignorePatterns: ['dist', '.eslintrc.cjs'],
    parser: '@typescript-eslint/parser',
    plugins: ['react-refresh'],
    rules: {
        'react-refresh/only-export-components': [
            'warn',
            { allowConstantExport: true },
        ],
        "no-var": "off",
        "prefer-const": "off",
        "@typescript-eslint/ban-ts-comment": "off",
        "no-extra-semi": "warn",
        "no-prototype-builtins": "off",
        "no-multiple-empty-lines": "warn",
        "block-spacing": "off",
        "max-len": "off",
        "no-undef": "off",
        "object-curly-spacing": "off",
        "no-unused-vars": "off",
        "indent": "off",
        "quotes": "off",
        "require-jsdoc": "off",
        "semi": "off",
        "padded-blocks": "off",
        "operator-linebreak": "off",
        "no-empty-pattern": "off",
        "no-trailing-spaces": "off",
        "eol-last": "off",
        "comma-dangle": "off",
        "new-cap": "off",
        "spaced-comment": "off",
        "quote-props": "off",
        "camelcase": "off",
        "linebreak-style": "off",
        "no-multi-spaces": "off",
        "space-before-function-paren": "off",
        "comma-spacing": "off",
        "brace-style": "off",
        "arrow-parens": "off",
        "@typescript-eslint/no-explicit-any": ["off"],
        "@typescript-eslint/ban-types": 'off',
        "@typescript-eslint/no-unused-vars": 'off',
        "react-hooks/exhaustive-deps": "off",
    },
}
